-- Crear la base de datos
CREATE DATABASE IF NOT EXISTS DB_SURVEYS;
USE DB_SURVEYS;

-- Tabla POLLS
CREATE TABLE POLLS (
    ID_POLL VARCHAR(36) PRIMARY KEY,
    NAME_POLL VARCHAR(100) NOT NULL,
    INFO_POLL VARCHAR(255),
    STARTDATE_POLL DATETIME,
    ENDINGDATE_POLL DATETIME,
    VISIBILITY_POLL BOOLEAN DEFAULT 1,
    COLOUR_POLL TINYINT,
    RANGE_POLL VARCHAR(50),
    STATUS TINYINT DEFAULT 1 -- 1 = Activo, 0 = Inactivo
);

-- Tabla OPTIONS
CREATE TABLE OPTIONS (
    ID_OPTION VARCHAR(36) PRIMARY KEY,
    ID_POLL VARCHAR(36),
    TITLE_OPTION VARCHAR(100) NOT NULL,
    INFO_OPTION VARCHAR(255),
    VOTES_OPTION INT DEFAULT 0,
    STATUS TINYINT DEFAULT 1, -- Soft delete
    FOREIGN KEY (ID_POLL) REFERENCES POLLS(ID_POLL)
);

-- Tabla CANDIDATES
CREATE TABLE CANDIDATES (
    ID_CANDIDATE VARCHAR(36) PRIMARY KEY,
    ID_POLL VARCHAR(36),
    NAME_CANDIDATE VARCHAR(100) NOT NULL,
    INFO_CANDIDATE VARCHAR(255),
    AGE_CANDIDATE TINYINT,
    CAREER_CANDIDATE VARCHAR(20),
    IDENTIFIER_CANDIDATE VARCHAR(15),
    COLLEGEID_CANDIDATE VARCHAR(15),
    VOTES_CANDIDATE INT DEFAULT 0,
    STATUS TINYINT DEFAULT 1, -- Soft delete
    FOREIGN KEY (ID_POLL) REFERENCES POLLS(ID_POLL)
);

-- Tabla VOTES
CREATE TABLE VOTES (
    ID_VOTE VARCHAR(36) PRIMARY KEY,
    ID_OPTION VARCHAR(36),
    ID_CANDIDATE VARCHAR(36),
    ID_USER VARCHAR(36) NOT NULL,
    STATUS TINYINT DEFAULT 1, -- Soft delete
    FOREIGN KEY (ID_OPTION) REFERENCES OPTIONS(ID_OPTION),
    FOREIGN KEY (ID_CANDIDATE) REFERENCES CANDIDATES(ID_CANDIDATE)
);