-- Crear la base de datos
CREATE DATABASE IF NOT EXISTS DB_SURVEYS;
USE DB_SURVEYS;

-- Tabla de usuarios (admin o creadores de encuestas)
CREATE TABLE USERS (
  ID_USER VARCHAR(36) PRIMARY KEY,
  USERNAME VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  ROLE ENUM('ADMIN', 'CREATOR') NOT NULL DEFAULT 'CREATOR',
  STATUS TINYINT DEFAULT 1
);

-- Tabla de encuestas
CREATE TABLE POLLS (
  ID_POLL VARCHAR(36) PRIMARY KEY,
  NAME_POLL VARCHAR(100) NOT NULL,
  INFO_POLL VARCHAR(255),
  STARTDATE_POLL DATETIME NOT NULL,
  ENDINGDATE_POLL DATETIME NOT NULL,
  VISIBILITY_POLL BOOLEAN,
  COLOUR_POLL TINYINT NOT NULL,
  RANGE_POLL VARCHAR(50),
  STATUS TINYINT DEFAULT 1,
  ID_USER VARCHAR(36),
  FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
);

-- Tabla de opciones de encuestas
CREATE TABLE OPTIONS (
  ID_OPTION VARCHAR(36) PRIMARY KEY,
  ID_POLL VARCHAR(36),
  TITLE_OPTION VARCHAR(100) NOT NULL,
  INFO_OPTION VARCHAR(255),
  VOTES_OPTION INT DEFAULT 0,
  STATUS TINYINT DEFAULT 1,
  PHOTO_OPTION VARCHAR(255),
  FOREIGN KEY (ID_POLL) REFERENCES POLLS(ID_POLL)
);

-- Tabla de candidatos
CREATE TABLE CANDIDATES (
  ID_CANDIDATE VARCHAR(36) PRIMARY KEY,
  ID_POLL VARCHAR(36),
  NAME_CANDIDATE VARCHAR(100) NOT NULL,
  INFO_CANDIDATE VARCHAR(255),
  AGE_CANDIDATE TINYINT,
  CARER_CANDIDATE VARCHAR(20),
  PHOTO_CANDIDATE VARCHAR(255),
  VOTES_CANDIDATE INT DEFAULT 0,
  STATUS TINYINT DEFAULT 1,
  FOREIGN KEY (ID_POLL) REFERENCES POLLS(ID_POLL)
);

-- Tabla de votos
CREATE TABLE VOTES (
  ID_VOTE VARCHAR(36) PRIMARY KEY,
  ID_OPTION VARCHAR(36),
  ID_CANDIDATE VARCHAR(36),
  USER_IDENTIFIER VARCHAR(50) NOT NULL,
  STATUS TINYINT DEFAULT 1,
  FOREIGN KEY (ID_OPTION) REFERENCES OPTIONS(ID_OPTION),
  FOREIGN KEY (ID_CANDIDATE) REFERENCES CANDIDATES(ID_CANDIDATE)
);